import React, { createContext, useContext, useState } from 'react';

type Language = 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.projects': 'Projecten',
    'nav.services': 'Diensten',
    'nav.sectors': 'Sectoren',
    'nav.team': 'Team',
    'nav.news': 'Nieuws',
    'nav.career': 'Carrière',
    'nav.contact': 'Neem contact op',
    
    // Hero Section
    'hero.title.ai': 'AI',
    'hero.title.transformation': 'TRANSFORMATIE',
    'hero.title.now': 'NU.',
    'hero.subtitle': 'Start uw AI-reis met een betrouwbare partner',
    'hero.cta1': 'Ontdek onze expertise',
    'hero.cta2': 'Bekijk projecten',
    
    // Stats Section
    'stats.title': 'Snel resultaat, hoge tevredenheid, meetbare impact',
    'stats.subtitle': 'We richten ons op wat ertoe doet: blije klanten, korte doorlooptijd en tastbare waarde.',
    'stats.satisfaction': 'klanttevredenheid',
    'stats.satisfaction.desc': 'Consistente waardering voor impact en samenwerking',
    'stats.weeks': 'weken tot prototype',
    'stats.weeks.desc': 'Van idee naar eerste werkende AI-oplossing in weken',
    'stats.productivity': 'productiviteitsverbetering',
    'stats.productivity.desc': 'Aantoonbare efficiency-winst bij implementaties',
    'stats.cta': 'Bekijk resultaten & cases',
    
    // Services Section
    'services.title': 'Onze diensten',
    'services.subtitle': 'Van AI-gedreven oplossingen tot volledige softwareontwikkeling - wij helpen bedrijven transformeren met cutting-edge technologie.',
    'services.ai.title': 'AI-gebaseerde oplossingen',
    'services.ai.desc': 'Op maat gemaakte, geavanceerde artificiële intelligentiesystemen die voldoen aan unieke behoeften',
    'services.software.title': 'Software ontwikkeling',
    'services.software.desc': 'Softwareoplossingen op maat, aangepast aan specifieke behoeften',
    'services.data.title': 'Gegevensbeheer',
    'services.data.desc': 'Gegevensarchitectuur optimaliseren voor verbeterde analyses',
    'services.innovation.title': 'Innovatiestrategie',
    'services.innovation.desc': 'Strategische verkenning en planning voor geavanceerde technologie voor kunstmatige intelligentie',
    'services.ux.title': 'UX & UI-ontwerp',
    'services.ux.desc': 'Intuïtieve, gebruiksvriendelijke interfaces maken voor naadloze systeemnavigatie',
    'services.ops.title': 'MLOps en DevOps',
    'services.ops.desc': 'Robuuste, efficiënte frameworks bouwen voor schaalbare, goed presterende oplossingen',
    'services.more': 'Meer informatie →',
    'services.cta': 'Bekijk alle diensten',
    
    // Case Studies Section
    'cases.title': 'Succesverhalen',
    'cases.subtitle': 'Ontdek hoe we complexe uitdagingen transformeren tot innovatieve oplossingen die echte impact hebben.',
    'cases.result': 'Resultaat:',
    'cases.view': 'Bekijk case study',
    'cases.cta': 'Bekijk alle projecten',
    
    // Testimonials Section
    'testimonials.title': 'Wat onze klanten zeggen',
    'testimonials.subtitle': 'Onze partnerships spreken voor zich. Hier zijn ervaringen van bedrijven die we hebben geholpen transformeren.',
    
    // Sectors Preview Section
    'sectors.title': 'Onze sectoren',
    'sectors.subtitle': 'Wij brengen diepgaande sectorkennis samen met cutting-edge AI-technologie.',
    'sectors.insurance.title': 'Middelgrote verzekeraars',
    'sectors.insurance.desc': 'AI-oplossingen voor risicobeoordeling, fraude detectie en klantservice optimalisatie in de verzekeringsbranche.',
    'sectors.professional.title': 'Professionele dienstverlening',
    'sectors.professional.desc': 'Automatisering en AI-ondersteuning voor advocatuur, consultancy en boekhouding om efficiëntie te verhogen.',
    'sectors.healthcare.title': 'Zorgsector',
    'sectors.healthcare.desc': 'AI-gedreven oplossingen voor klinieken, zorggroepen en kleinere zorginstelling voor betere patiëntenzorg.',
    'sectors.cta': 'Meer ontdekken',
    
    // CTA Section
    'cta.title': 'Wil je een project starten?',
    'cta.subtitle': "Let's talk",
    'cta.description': 'Klaar om uw bedrijf te transformeren met AI? Laten we bespreken hoe we uw uitdagingen kunnen omzetten in innovatieve oplossingen.',
    'cta.contact': 'Neem contact met ons op',
    'cta.projects': 'Bekijk onze projecten',
    'cta.call': 'Of bel ons direct:',
    'cta.phone': '+32 2 123 45 67',
    
    // Partners Section
    'partners.title': 'Verenigingen en bedrijven waar we met trots mee samenwerken',
    'partners.footer': 'En vele andere innovatieve partners in AI en technologie',
    
    // Projects Page
    'projects.title': 'Onze',
    'projects.title.highlight': 'Projecten',
    'projects.subtitle': 'Ontdek hoe we complexe uitdagingen transformeren tot innovatieve AI-oplossingen voor bedrijven in verschillende sectoren.',
    'projects.read.more': 'Lees meer →',
    'projects.cta.title': 'Heeft u een project in gedachten?',
    'projects.cta.subtitle': 'Laten we samen bespreken hoe we uw uitdaging kunnen omzetten in een innovatieve oplossing.',
    'projects.cta.button': 'Start uw project',
    
    // Services Page  
    'services.page.title': 'Onze',
    'services.page.title.highlight': 'Diensten',
    'services.page.subtitle': 'Van AI-gedreven oplossingen tot volledige softwareontwikkeling - wij helpen bedrijven transformeren met cutting-edge technologie.',
    'services.ai.features.ml': 'Machine Learning',
    'services.ai.features.dl': 'Deep Learning',
    'services.ai.features.cv': 'Computer Vision',
    'services.ai.features.nlp': 'Natural Language Processing',
    'services.software.features.custom': 'Custom Development',
    'services.software.features.api': 'API Integration',
    'services.software.features.cloud': 'Cloud Solutions',
    'services.software.features.mobile': 'Mobile Apps',
    'services.data.features.arch': 'Data Architecture',
    'services.data.features.etl': 'ETL Pipelines',
    'services.data.features.warehouse': 'Data Warehousing',
    'services.data.features.analytics': 'Analytics',
    'services.innovation.features.roadmap': 'Innovation Roadmap',
    'services.innovation.features.assessment': 'Technology Assessment',
    'services.innovation.features.strategy': 'Digital Strategy',
    'services.innovation.features.consulting': 'R&D Consulting',
    'services.ux.features.research': 'User Research',
    'services.ux.features.design': 'Interface Design',
    'services.ux.features.prototype': 'Prototyping',
    'services.ux.features.testing': 'Usability Testing',
    'services.ops.features.cicd': 'CI/CD Pipelines',
    'services.ops.features.deployment': 'Model Deployment',
    'services.ops.features.infrastructure': 'Infrastructure',
    'services.ops.features.monitoring': 'Monitoring',
    'services.additional.title': 'Aanvullende',
    'services.additional.title.highlight': 'Specialisaties',
    'services.performance.title': 'Performance Optimization',
    'services.performance.desc': 'Systeemprestaties verbeteren',
    'services.security.title': 'Security Consulting',
    'services.security.desc': 'Veiligheid en compliance waarborgen',
    'services.bi.title': 'Business Intelligence',
    'services.bi.desc': 'Data-gedreven besluitvorming',
    'services.automation.title': 'Process Automation',
    'services.automation.desc': 'Bedrijfsprocessen automatiseren',
    'services.final.cta.title': 'Klaar om uw project te starten?',
    'services.final.cta.subtitle': 'Laten we bespreken hoe onze expertise uw bedrijf naar het volgende niveau kan tillen.',
    'services.final.cta.contact': 'Neem contact op',
    'services.final.cta.projects': 'Bekijk onze projecten',
    
    // Specializations/Sectors Page
    'specializations.title': 'Onze',
    'specializations.title.highlight': 'Sectoren',
    'specializations.subtitle': 'Wij brengen diepgaande sectorkennis samen met cutting-edge AI-technologie om specifieke uitdagingen in verschillende industrieën op te lossen.',
    'specializations.focus': 'Sector Focus',
    'specializations.solutions': 'Onze oplossingen:',
    'specializations.case.study': 'Case Study:',
    'specializations.more.about': 'Meer over',
    'specializations.view.projects': 'Bekijk projecten',
    'specializations.not.listed.title': 'Uw sector niet vermeld?',
    'specializations.not.listed.desc': 'Wij werken met bedrijven in diverse sectoren. Neem contact met ons op om te bespreken hoe we uw specifieke uitdagingen kunnen oplossen.',
    'specializations.not.listed.cta': 'Bespreek uw project',
    
    // Footer
    'footer.description': 'Cogniq AI transformeert bedrijven met innovatieve AI-oplossingen. Van strategie tot implementatie, wij zijn uw betrouwbare partner in de AI-revolutie.',
    'footer.company': 'Bedrijf',
    'footer.services': 'Diensten',
    'footer.sectors': 'Sectoren',
    'footer.company.about': 'Over ons',
    'footer.company.team': 'Team',
    'footer.company.career': 'Carrière',
    'footer.company.news': 'Nieuws',
    'footer.services.ai': 'AI-oplossingen',
    'footer.services.software': 'Software ontwikkeling',
    'footer.services.data': 'Data engineering',
    'footer.services.consultancy': 'Consultancy',
    'footer.sectors.healthcare': 'Gezondheidszorg',
    'footer.sectors.energy': 'Energie',
    'footer.sectors.pharma': 'Farmaceutisch',
    'footer.sectors.transport': 'Transport',
    'footer.legal.privacy': 'Privacy beleid',
    'footer.legal.terms': 'Algemene voorwaarden',
    'footer.legal.cookies': 'Cookies',
    'footer.legal.gdpr': 'GDPR',
    'footer.copyright': '© 2024 Cogniq AI. Alle rechten voorbehouden.',
    
    // Team Page
    'team.title': 'Ons',
    'team.title.highlight': 'Team',
    'team.subtitle': 'Ontmoet de experts achter onze AI-oplossingen. Een divers team van data scientists, engineers en consultants.',
    'team.hero.title': 'Samen bouwen we de toekomst van AI',
    'team.hero.desc': 'Ons multidisciplinaire team combineert technische expertise met branchekennis',
    'team.departments.title': 'Onze',
    'team.departments.highlight': 'Afdelingen',
    'team.members.title': 'Ons',
    'team.members.highlight': 'Team',
    'team.join.title': 'Word deel van ons team',
    'team.join.desc': 'We zijn altijd op zoek naar getalenteerde professionals die willen bijdragen aan de toekomst van AI.',
    'team.join.cta1': 'Bekijk vacatures',
    'team.join.cta2': 'Neem contact op',
    
    // Career Page
    'career.title': 'Carrière bij',
    'career.title.highlight': 'Cogniq AI',
    'career.subtitle': 'Word deel van een team dat de toekomst van AI vormgeeft. Bij Cogniq AI combineren we technische excellentie met een geweldige werkcultuur.',
    'career.why.title': 'Waarom werken bij',
    'career.why.highlight': 'Cogniq AI',
    'career.why.item1': 'Werken aan cutting-edge AI projecten voor toonaangevende bedrijven',
    'career.why.item2': 'Samenwerken met een multidisciplinair team van experts',
    'career.why.item3': 'Bijdragen aan open-source projecten en onderzoekspublicaties',
    'career.why.item4': 'Persoonlijke groei in een dynamische en innovatieve omgeving',
    'career.why.item5': 'Impact maken op de toekomst van AI in verschillende sectoren',
    'career.experts': 'Experts in ons team',
    'career.experience': 'Jaar ervaring',
    'career.projects.count': 'Projecten',
    'career.benefits.title': 'Onze',
    'career.benefits.highlight': 'Voordelen',
    'career.benefit.flexible.title': 'Flexibel werken',
    'career.benefit.flexible.desc': 'Hybride werkmodel met moderne apparatuur en flexibele werkuren',
    'career.benefit.learning.title': 'Leren & ontwikkeling',
    'career.benefit.learning.desc': 'Conferenties, trainingen en tijd voor persoonlijke projecten',
    'career.benefit.balance.title': 'Werk-leven balans',
    'career.benefit.balance.desc': 'Ruime vakantieregeling en mentale gezondheidsondersteuning',
    'career.benefit.package.title': 'Competitief pakket',
    'career.benefit.package.desc': 'Marktconform salaris, bonussen en aandelen opties',
    'career.benefit.culture.title': 'Geweldige cultuur',
    'career.benefit.culture.desc': 'Team events, gratis lunch en gezellige kantooromgeving',
    'career.positions.title': 'Open',
    'career.positions.highlight': 'Posities',
    'career.positions.featured': 'Featured',
    'career.positions.apply': 'Solliciteer nu',
    'career.positions.details': 'Meer details',
    'career.positions.requirements': 'Vereisten:',
    'career.process.title': 'Sollicitatieproces',
    'career.process.step1.title': 'Sollicitatie',
    'career.process.step1.desc': 'Verstuur je CV en motivatiebrief',
    'career.process.step2.title': 'Screening',
    'career.process.step2.desc': 'Eerste gesprek met HR',
    'career.process.step3.title': 'Technisch interview',
    'career.process.step3.desc': 'Gesprek met het team',
    'career.process.step4.title': 'Aanbod',
    'career.process.step4.desc': 'Welkom bij Cogniq AI!',
    'career.process.open.text': 'Zie je geen passende functie? Stuur ons een open sollicitatie - we horen graag van getalenteerde professionals!',
    'career.process.open.cta': 'Open sollicitatie',
    
    // Contact Page
    'contact.title': 'Neem',
    'contact.title.highlight': 'Contact',
    'contact.title.suffix': 'Op',
    'contact.subtitle': 'Klaar om uw AI-project te starten? Neem contact met ons op en laten we bespreken hoe we uw uitdagingen kunnen oplossen.',
    'contact.info.title': 'Contactinformatie',
    'contact.office.main': 'Hoofdkantoor',
    'contact.office.antwerp': 'Vestiging',
    'contact.phone': 'Telefoon',
    'contact.email': 'E-mail',
    'contact.hours': 'Openingstijden',
    'contact.form.title': 'Stuur ons een bericht',
    'contact.form.name': 'Volledige naam',
    'contact.form.name.placeholder': 'Jan Janssen',
    'contact.form.email': 'E-mailadres',
    'contact.form.email.placeholder': 'jan@voorbeeld.nl',
    'contact.form.company': 'Bedrijf',
    'contact.form.company.placeholder': 'Uw bedrijfsnaam',
    'contact.form.subject': 'Onderwerp',
    'contact.form.subject.placeholder': 'Waar kunnen we u mee helpen?',
    'contact.form.message': 'Bericht',
    'contact.form.message.placeholder': 'Vertel ons over uw project of uitdaging...',
    'contact.form.submit': 'Verstuur bericht',
    'contact.form.privacy': 'We respecteren uw privacy. Uw gegevens worden niet gedeeld met derden.',
    'contact.map.title': 'Bezoek ons kantoor',
    'contact.faq.title': 'Veelgestelde vragen',
    'contact.faq.q1': 'Wat kost een AI-project?',
    'contact.faq.a1': 'Kosten worden bepaald op basis van projectvereisten. Neem contact op voor een offerte.',
    'contact.faq.cta': 'Meer veelgestelde vragen',
    
    // News Page
    'news.title': 'Nieuws &',
    'news.title.highlight': 'Updates',
    'news.subtitle': 'Blijf op de hoogte van de laatste ontwikkelingen, projecten en innovaties bij Cogniq AI.',
    'news.categories': 'Categorieën',
    'news.featured': 'Featured',
    'news.read.more': 'Lees meer',
    'news.newsletter.title': 'Blijf op de hoogte',
    'news.newsletter.desc': 'Ontvang onze nieuwsbrief en mis geen enkel update over AI innovaties en bedrijfsinzichten.',
    'news.newsletter.placeholder': 'Uw e-mailadres',
    'news.newsletter.cta': 'Abonneren',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.services': 'Services',
    'nav.sectors': 'Sectors',
    'nav.team': 'Team',
    'nav.news': 'News',
    'nav.career': 'Career',
    'nav.contact': 'Get in touch',
    
    // Hero Section
    'hero.title.ai': 'AI',
    'hero.title.transformation': 'TRANSFORMATION',
    'hero.title.now': 'NOW.',
    'hero.subtitle': 'Start your AI journey with a trusted partner',
    'hero.cta1': 'Discover our expertise',
    'hero.cta2': 'View projects',
    
    // Stats Section
    'stats.title': 'Fast results, high satisfaction, measurable impact',
    'stats.subtitle': 'We focus on what matters: happy clients, short delivery times and tangible value.',
    'stats.satisfaction': 'customer satisfaction',
    'stats.satisfaction.desc': 'Consistent rating for impact and collaboration',
    'stats.weeks': 'weeks to prototype',
    'stats.weeks.desc': 'From idea to first working AI solution in weeks',
    'stats.productivity': 'productivity improvement',
    'stats.productivity.desc': 'Demonstrable efficiency gains in implementations',
    'stats.cta': 'View results & cases',
    
    // Services Section
    'services.title': 'Our services',
    'services.subtitle': 'From AI-driven solutions to full software development - we help businesses transform with cutting-edge technology.',
    'services.ai.title': 'AI-powered solutions',
    'services.ai.desc': 'Custom-built, advanced artificial intelligence systems that meet unique needs',
    'services.software.title': 'Software development',
    'services.software.desc': 'Custom software solutions, tailored to specific needs',
    'services.data.title': 'Data management',
    'services.data.desc': 'Optimize data architecture for improved analytics',
    'services.innovation.title': 'Innovation strategy',
    'services.innovation.desc': 'Strategic exploration and planning for advanced artificial intelligence technology',
    'services.ux.title': 'UX & UI design',
    'services.ux.desc': 'Create intuitive, user-friendly interfaces for seamless system navigation',
    'services.ops.title': 'MLOps and DevOps',
    'services.ops.desc': 'Build robust, efficient frameworks for scalable, high-performing solutions',
    'services.more': 'More information →',
    'services.cta': 'View all services',
    
    // Case Studies Section
    'cases.title': 'Success stories',
    'cases.subtitle': 'Discover how we transform complex challenges into innovative solutions that have real impact.',
    'cases.result': 'Result:',
    'cases.view': 'View case study',
    'cases.cta': 'View all projects',
    
    // Testimonials Section
    'testimonials.title': 'What our clients say',
    'testimonials.subtitle': 'Our partnerships speak for themselves. Here are experiences from companies we have helped transform.',
    
    // Sectors Preview Section
    'sectors.title': 'Our sectors',
    'sectors.subtitle': 'We combine deep sector knowledge with cutting-edge AI technology.',
    'sectors.insurance.title': 'Mid-size insurers',
    'sectors.insurance.desc': 'AI solutions for risk assessment, fraud detection and customer service optimization in the insurance industry.',
    'sectors.professional.title': 'Professional services',
    'sectors.professional.desc': 'Automation and AI support for legal, consultancy and accounting to increase efficiency.',
    'sectors.healthcare.title': 'Healthcare sector',
    'sectors.healthcare.desc': 'AI-driven solutions for clinics, care groups and smaller healthcare institutions for better patient care.',
    'sectors.cta': 'Discover more',
    
    // CTA Section
    'cta.title': 'Want to start a project?',
    'cta.subtitle': "Let's talk",
    'cta.description': 'Ready to transform your business with AI? Let us discuss how we can turn your challenges into innovative solutions.',
    'cta.contact': 'Get in touch with us',
    'cta.projects': 'View our projects',
    'cta.call': 'Or call us directly:',
    'cta.phone': '+32 2 123 45 67',
    
    // Partners Section
    'partners.title': 'Associations and companies we proudly collaborate with',
    'partners.footer': 'And many other innovative partners in AI and technology',
    
    // Projects Page
    'projects.title': 'Our',
    'projects.title.highlight': 'Projects',
    'projects.subtitle': 'Discover how we transform complex challenges into innovative AI solutions for businesses across different sectors.',
    'projects.read.more': 'Read more →',
    'projects.cta.title': 'Do you have a project in mind?',
    'projects.cta.subtitle': 'Let us discuss together how we can turn your challenge into an innovative solution.',
    'projects.cta.button': 'Start your project',
    
    // Services Page
    'services.page.title': 'Our',
    'services.page.title.highlight': 'Services',
    'services.page.subtitle': 'From AI-driven solutions to full software development - we help businesses transform with cutting-edge technology.',
    'services.ai.features.ml': 'Machine Learning',
    'services.ai.features.dl': 'Deep Learning',
    'services.ai.features.cv': 'Computer Vision',
    'services.ai.features.nlp': 'Natural Language Processing',
    'services.software.features.custom': 'Custom Development',
    'services.software.features.api': 'API Integration',
    'services.software.features.cloud': 'Cloud Solutions',
    'services.software.features.mobile': 'Mobile Apps',
    'services.data.features.arch': 'Data Architecture',
    'services.data.features.etl': 'ETL Pipelines',
    'services.data.features.warehouse': 'Data Warehousing',
    'services.data.features.analytics': 'Analytics',
    'services.innovation.features.roadmap': 'Innovation Roadmap',
    'services.innovation.features.assessment': 'Technology Assessment',
    'services.innovation.features.strategy': 'Digital Strategy',
    'services.innovation.features.consulting': 'R&D Consulting',
    'services.ux.features.research': 'User Research',
    'services.ux.features.design': 'Interface Design',
    'services.ux.features.prototype': 'Prototyping',
    'services.ux.features.testing': 'Usability Testing',
    'services.ops.features.cicd': 'CI/CD Pipelines',
    'services.ops.features.deployment': 'Model Deployment',
    'services.ops.features.infrastructure': 'Infrastructure',
    'services.ops.features.monitoring': 'Monitoring',
    'services.additional.title': 'Additional',
    'services.additional.title.highlight': 'Specializations',
    'services.performance.title': 'Performance Optimization',
    'services.performance.desc': 'Improve system performance',
    'services.security.title': 'Security Consulting',
    'services.security.desc': 'Ensure security and compliance',
    'services.bi.title': 'Business Intelligence',
    'services.bi.desc': 'Data-driven decision making',
    'services.automation.title': 'Process Automation',
    'services.automation.desc': 'Automate business processes',
    'services.final.cta.title': 'Ready to start your project?',
    'services.final.cta.subtitle': 'Let us discuss how our expertise can take your business to the next level.',
    'services.final.cta.contact': 'Get in touch',
    'services.final.cta.projects': 'View our projects',
    
    // Specializations/Sectors Page
    'specializations.title': 'Our',
    'specializations.title.highlight': 'Sectors',
    'specializations.subtitle': 'We combine deep sector knowledge with cutting-edge AI technology to solve specific challenges in different industries.',
    'specializations.focus': 'Sector Focus',
    'specializations.solutions': 'Our solutions:',
    'specializations.case.study': 'Case Study:',
    'specializations.more.about': 'More about',
    'specializations.view.projects': 'View projects',
    'specializations.not.listed.title': 'Your sector not listed?',
    'specializations.not.listed.desc': 'We work with companies in various sectors. Contact us to discuss how we can solve your specific challenges.',
    'specializations.not.listed.cta': 'Discuss your project',
    
    // Footer
    'footer.description': 'Cogniq AI transforms businesses with innovative AI solutions. From strategy to implementation, we are your trusted partner in the AI revolution.',
    'footer.company': 'Company',
    'footer.services': 'Services',
    'footer.sectors': 'Sectors',
    'footer.company.about': 'About us',
    'footer.company.team': 'Team',
    'footer.company.career': 'Career',
    'footer.company.news': 'News',
    'footer.services.ai': 'AI solutions',
    'footer.services.software': 'Software development',
    'footer.services.data': 'Data engineering',
    'footer.services.consultancy': 'Consultancy',
    'footer.sectors.healthcare': 'Healthcare',
    'footer.sectors.energy': 'Energy',
    'footer.sectors.pharma': 'Pharmaceutical',
    'footer.sectors.transport': 'Transport',
    'footer.legal.privacy': 'Privacy policy',
    'footer.legal.terms': 'Terms and conditions',
    'footer.legal.cookies': 'Cookies',
    'footer.legal.gdpr': 'GDPR',
    'footer.copyright': '© 2024 Cogniq AI. All rights reserved.',
    
    // Team Page
    'team.title': 'Our',
    'team.title.highlight': 'Team',
    'team.subtitle': 'Meet the experts behind our AI solutions. A diverse team of data scientists, engineers and consultants.',
    'team.hero.title': 'Together we build the future of AI',
    'team.hero.desc': 'Our multidisciplinary team combines technical expertise with industry knowledge',
    'team.departments.title': 'Our',
    'team.departments.highlight': 'Departments',
    'team.members.title': 'Our',
    'team.members.highlight': 'Team',
    'team.join.title': 'Join our team',
    'team.join.desc': 'We are always looking for talented professionals who want to contribute to the future of AI.',
    'team.join.cta1': 'View vacancies',
    'team.join.cta2': 'Get in touch',
    
    // Career Page
    'career.title': 'Career at',
    'career.title.highlight': 'Cogniq AI',
    'career.subtitle': 'Join a team shaping the future of AI. At Cogniq AI we combine technical excellence with a great work culture.',
    'career.why.title': 'Why work at',
    'career.why.highlight': 'Cogniq AI',
    'career.why.item1': 'Work on cutting-edge AI projects for leading companies',
    'career.why.item2': 'Collaborate with a multidisciplinary team of experts',
    'career.why.item3': 'Contribute to open-source projects and research publications',
    'career.why.item4': 'Personal growth in a dynamic and innovative environment',
    'career.why.item5': 'Make an impact on the future of AI in various sectors',
    'career.experts': 'Experts on our team',
    'career.experience': 'Years experience',
    'career.projects.count': 'Projects',
    'career.benefits.title': 'Our',
    'career.benefits.highlight': 'Benefits',
    'career.benefit.flexible.title': 'Flexible working',
    'career.benefit.flexible.desc': 'Hybrid work model with modern equipment and flexible hours',
    'career.benefit.learning.title': 'Learning & development',
    'career.benefit.learning.desc': 'Conferences, training and time for personal projects',
    'career.benefit.balance.title': 'Work-life balance',
    'career.benefit.balance.desc': 'Generous vacation policy and mental health support',
    'career.benefit.package.title': 'Competitive package',
    'career.benefit.package.desc': 'Market-competitive salary, bonuses and stock options',
    'career.benefit.culture.title': 'Great culture',
    'career.benefit.culture.desc': 'Team events, free lunch and cozy office environment',
    'career.positions.title': 'Open',
    'career.positions.highlight': 'Positions',
    'career.positions.featured': 'Featured',
    'career.positions.apply': 'Apply now',
    'career.positions.details': 'More details',
    'career.positions.requirements': 'Requirements:',
    'career.process.title': 'Application process',
    'career.process.step1.title': 'Application',
    'career.process.step1.desc': 'Send your CV and motivation letter',
    'career.process.step2.title': 'Screening',
    'career.process.step2.desc': 'Initial interview with HR',
    'career.process.step3.title': 'Technical interview',
    'career.process.step3.desc': 'Interview with the team',
    'career.process.step4.title': 'Offer',
    'career.process.step4.desc': 'Welcome to Cogniq AI!',
    'career.process.open.text': "Don't see a suitable position? Send us an open application - we'd love to hear from talented professionals!",
    'career.process.open.cta': 'Open application',
    
    // Contact Page
    'contact.title': 'Get in',
    'contact.title.highlight': 'Touch',
    'contact.title.suffix': '',
    'contact.subtitle': 'Ready to start your AI project? Get in touch and let us discuss how we can solve your challenges.',
    'contact.info.title': 'Contact information',
    'contact.office.main': 'Head office',
    'contact.office.antwerp': 'Branch',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Opening hours',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Full name',
    'contact.form.name.placeholder': 'John Doe',
    'contact.form.email': 'Email address',
    'contact.form.email.placeholder': 'john@example.com',
    'contact.form.company': 'Company',
    'contact.form.company.placeholder': 'Your company name',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'How can we help you?',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your project or challenge...',
    'contact.form.submit': 'Send message',
    'contact.form.privacy': 'We respect your privacy. Your data will not be shared with third parties.',
    'contact.map.title': 'Visit our office',
    'contact.faq.title': 'Frequently asked questions',
    'contact.faq.q1': 'What does an AI project cost?',
    'contact.faq.a1': 'Costs are determined based on project requirements. Contact us for a quote.',
    'contact.faq.cta': 'More frequently asked questions',
    
    // News Page
    'news.title': 'News &',
    'news.title.highlight': 'Updates',
    'news.subtitle': 'Stay informed about the latest developments, projects and innovations at Cogniq AI.',
    'news.categories': 'Categories',
    'news.featured': 'Featured',
    'news.read.more': 'Read more',
    'news.newsletter.title': 'Stay informed',
    'news.newsletter.desc': 'Receive our newsletter and don\'t miss any updates about AI innovations and business insights.',
    'news.newsletter.placeholder': 'Your email address',
    'news.newsletter.cta': 'Subscribe',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('nl');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['nl']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};