import React, { createContext, useContext, useState } from 'react';

type Language = 'nl' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  nl: {
    // Navigation
    'nav.home': 'Home',
    'nav.projects': 'Projecten',
    'nav.services': 'Diensten',
    'nav.sectors': 'Sectoren',
    'nav.team': 'Team',
    'nav.news': 'Nieuws',
    'nav.career': 'Carrière',
    'nav.contact': 'Neem contact op',
    
    // Hero Section
    'hero.title.ai': 'AI',
    'hero.title.transformation': 'TRANSFORMATIE',
    'hero.title.now': 'NU.',
    'hero.subtitle': 'Start uw AI-reis met een betrouwbare partner',
    'hero.cta1': 'Ontdek onze expertise',
    'hero.cta2': 'Bekijk projecten',
    
    // Stats Section
    'stats.title': 'Snel resultaat, hoge tevredenheid, meetbare impact',
    'stats.subtitle': 'We richten ons op wat ertoe doet: blije klanten, korte doorlooptijd en tastbare waarde.',
    'stats.satisfaction': 'klanttevredenheid',
    'stats.satisfaction.desc': 'Consistente waardering voor impact en samenwerking',
    'stats.weeks': 'weken tot prototype',
    'stats.weeks.desc': 'Van idee naar eerste werkende AI-oplossing in weken',
    'stats.productivity': 'productiviteitsverbetering',
    'stats.productivity.desc': 'Aantoonbare efficiency-winst bij implementaties',
    'stats.cta': 'Bekijk resultaten & cases',
    
    // Services Section
    'services.title': 'Onze diensten',
    'services.subtitle': 'Van AI-gedreven oplossingen tot volledige softwareontwikkeling - wij helpen bedrijven transformeren met cutting-edge technologie.',
    'services.ai.title': 'AI-gebaseerde oplossingen',
    'services.ai.desc': 'Op maat gemaakte, geavanceerde artificiële intelligentiesystemen die voldoen aan unieke behoeften',
    'services.software.title': 'Software ontwikkeling',
    'services.software.desc': 'Softwareoplossingen op maat, aangepast aan specifieke behoeften',
    'services.data.title': 'Gegevensbeheer',
    'services.data.desc': 'Gegevensarchitectuur optimaliseren voor verbeterde analyses',
    'services.innovation.title': 'Innovatiestrategie',
    'services.innovation.desc': 'Strategische verkenning en planning voor geavanceerde technologie voor kunstmatige intelligentie',
    'services.ux.title': 'UX & UI-ontwerp',
    'services.ux.desc': 'Intuïtieve, gebruiksvriendelijke interfaces maken voor naadloze systeemnavigatie',
    'services.ops.title': 'MLOps en DevOps',
    'services.ops.desc': 'Robuuste, efficiënte frameworks bouwen voor schaalbare, goed presterende oplossingen',
    'services.more': 'Meer informatie →',
    'services.cta': 'Bekijk alle diensten',
    
    // Case Studies Section
    'cases.title': 'Succesverhalen',
    'cases.subtitle': 'Ontdek hoe we complexe uitdagingen transformeren tot innovatieve oplossingen die echte impact hebben.',
    'cases.result': 'Resultaat:',
    'cases.view': 'Bekijk case study',
    'cases.cta': 'Bekijk alle projecten',
    
    // Testimonials Section
    'testimonials.title': 'Wat onze klanten zeggen',
    'testimonials.subtitle': 'Onze partnerships spreken voor zich. Hier zijn ervaringen van bedrijven die we hebben geholpen transformeren.',
    
    // Sectors Preview Section
    'sectors.title': 'Onze sectoren',
    'sectors.subtitle': 'Wij brengen diepgaande sectorkennis samen met cutting-edge AI-technologie.',
    'sectors.insurance.title': 'Middelgrote verzekeraars',
    'sectors.insurance.desc': 'AI-oplossingen voor risicobeoordeling, fraude detectie en klantservice optimalisatie in de verzekeringsbranche.',
    'sectors.professional.title': 'Professionele dienstverlening',
    'sectors.professional.desc': 'Automatisering en AI-ondersteuning voor advocatuur, consultancy en boekhouding om efficiëntie te verhogen.',
    'sectors.healthcare.title': 'Zorgsector',
    'sectors.healthcare.desc': 'AI-gedreven oplossingen voor klinieken, zorggroepen en kleinere zorginstelling voor betere patiëntenzorg.',
    'sectors.cta': 'Meer ontdekken',
    
    // CTA Section
    'cta.title': 'Wil je een project starten?',
    'cta.subtitle': "Let's talk",
    'cta.description': 'Klaar om uw bedrijf te transformeren met AI? Laten we bespreken hoe we uw uitdagingen kunnen omzetten in innovatieve oplossingen.',
    'cta.contact': 'Neem contact met ons op',
    'cta.projects': 'Bekijk onze projecten',
    'cta.call': 'Of bel ons direct:',
    'cta.phone': '+32 2 123 45 67',
    
    // Partners Section
    'partners.title': 'Verenigingen en bedrijven waar we met trots mee samenwerken',
    'partners.footer': 'En vele andere innovatieve partners in AI en technologie',
    
    // Projects Page
    'projects.title': 'Onze',
    'projects.title.highlight': 'Projecten',
    'projects.subtitle': 'Ontdek hoe we complexe uitdagingen transformeren tot innovatieve AI-oplossingen voor bedrijven in verschillende sectoren.',
    'projects.read.more': 'Lees meer →',
    'projects.cta.title': 'Heeft u een project in gedachten?',
    'projects.cta.subtitle': 'Laten we samen bespreken hoe we uw uitdaging kunnen omzetten in een innovatieve oplossing.',
    'projects.cta.button': 'Start uw project',
    
    // Services Page  
    'services.page.title': 'Onze',
    'services.page.title.highlight': 'Diensten',
    'services.page.subtitle': 'Van AI-gedreven oplossingen tot volledige softwareontwikkeling - wij helpen bedrijven transformeren met cutting-edge technologie.',
    'services.ai.features.ml': 'Machine Learning',
    'services.ai.features.dl': 'Deep Learning',
    'services.ai.features.cv': 'Computer Vision',
    'services.ai.features.nlp': 'Natural Language Processing',
    'services.software.features.custom': 'Custom Development',
    'services.software.features.api': 'API Integration',
    'services.software.features.cloud': 'Cloud Solutions',
    'services.software.features.mobile': 'Mobile Apps',
    'services.data.features.arch': 'Data Architecture',
    'services.data.features.etl': 'ETL Pipelines',
    'services.data.features.warehouse': 'Data Warehousing',
    'services.data.features.analytics': 'Analytics',
    'services.innovation.features.roadmap': 'Innovation Roadmap',
    'services.innovation.features.assessment': 'Technology Assessment',
    'services.innovation.features.strategy': 'Digital Strategy',
    'services.innovation.features.consulting': 'R&D Consulting',
    'services.ux.features.research': 'User Research',
    'services.ux.features.design': 'Interface Design',
    'services.ux.features.prototype': 'Prototyping',
    'services.ux.features.testing': 'Usability Testing',
    'services.ops.features.cicd': 'CI/CD Pipelines',
    'services.ops.features.deployment': 'Model Deployment',
    'services.ops.features.infrastructure': 'Infrastructure',
    'services.ops.features.monitoring': 'Monitoring',
    'services.additional.title': 'Aanvullende',
    'services.additional.title.highlight': 'Specialisaties',
    'services.performance.title': 'Performance Optimization',
    'services.performance.desc': 'Systeemprestaties verbeteren',
    'services.security.title': 'Security Consulting',
    'services.security.desc': 'Veiligheid en compliance waarborgen',
    'services.bi.title': 'Business Intelligence',
    'services.bi.desc': 'Data-gedreven besluitvorming',
    'services.automation.title': 'Process Automation',
    'services.automation.desc': 'Bedrijfsprocessen automatiseren',
    'services.final.cta.title': 'Klaar om uw project te starten?',
    'services.final.cta.subtitle': 'Laten we bespreken hoe onze expertise uw bedrijf naar het volgende niveau kan tillen.',
    'services.final.cta.contact': 'Neem contact op',
    'services.final.cta.projects': 'Bekijk onze projecten',
    
    // Specializations/Sectors Page
    'specializations.title': 'Onze',
    'specializations.title.highlight': 'Sectoren',
    'specializations.subtitle': 'Wij brengen diepgaande sectorkennis samen met cutting-edge AI-technologie om specifieke uitdagingen in verschillende industrieën op te lossen.',
    'specializations.focus': 'Sector Focus',
    'specializations.solutions': 'Onze oplossingen:',
    'specializations.case.study': 'Case Study:',
    'specializations.more.about': 'Meer over',
    'specializations.view.projects': 'Bekijk projecten',
    'specializations.not.listed.title': 'Uw sector niet vermeld?',
    'specializations.not.listed.desc': 'Wij werken met bedrijven in diverse sectoren. Neem contact met ons op om te bespreken hoe we uw specifieke uitdagingen kunnen oplossen.',
    'specializations.not.listed.cta': 'Bespreek uw project',
    
    // Footer
    'footer.description': 'Cogniq AI transformeert bedrijven met innovatieve AI-oplossingen. Van strategie tot implementatie, wij zijn uw betrouwbare partner in de AI-revolutie.',
    'footer.company': 'Bedrijf',
    'footer.services': 'Diensten',
    'footer.sectors': 'Sectoren',
    'footer.company.about': 'Over ons',
    'footer.company.team': 'Team',
    'footer.company.career': 'Carrière',
    'footer.company.news': 'Nieuws',
    'footer.services.ai': 'AI-oplossingen',
    'footer.services.software': 'Software ontwikkeling',
    'footer.services.data': 'Data engineering',
    'footer.services.consultancy': 'Consultancy',
    'footer.sectors.healthcare': 'Gezondheidszorg',
    'footer.sectors.energy': 'Energie',
    'footer.sectors.pharma': 'Farmaceutisch',
    'footer.sectors.transport': 'Transport',
    'footer.legal.privacy': 'Privacy beleid',
    'footer.legal.terms': 'Algemene voorwaarden',
    'footer.legal.cookies': 'Cookies',
    'footer.legal.gdpr': 'GDPR',
    'footer.copyright': '© 2024 Cogniq AI. Alle rechten voorbehouden.',
    
    // Team Page
    'team.title': 'Ons',
    'team.title.highlight': 'Team',
    'team.subtitle': 'Ontmoet de experts achter onze AI-oplossingen. Een divers team van data scientists, engineers en consultants.',
    'team.hero.title': 'Samen bouwen we de toekomst van AI',
    'team.hero.desc': 'Ons multidisciplinaire team combineert technische expertise met branchekennis',
    'team.departments.title': 'Onze',
    'team.departments.highlight': 'Afdelingen',
    'team.members.title': 'Ons',
    'team.members.highlight': 'Team',
    'team.join.title': 'Word deel van ons team',
    'team.join.desc': 'We zijn altijd op zoek naar getalenteerde professionals die willen bijdragen aan de toekomst van AI.',
    'team.join.cta1': 'Bekijk vacatures',
    'team.join.cta2': 'Neem contact op',
    
    // Career Page
    'career.title': 'Carrière bij',
    'career.title.highlight': 'Cogniq AI',
    'career.subtitle': 'Word deel van een team dat de toekomst van AI vormgeeft. Bij Cogniq AI combineren we technische excellentie met een geweldige werkcultuur.',
    'career.why.title': 'Waarom werken bij',
    'career.why.highlight': 'Cogniq AI',
    'career.why.item1': 'Werken aan cutting-edge AI projecten voor toonaangevende bedrijven',
    'career.why.item2': 'Samenwerken met een multidisciplinair team van experts',
    'career.why.item3': 'Bijdragen aan open-source projecten en onderzoekspublicaties',
    'career.why.item4': 'Persoonlijke groei in een dynamische en innovatieve omgeving',
    'career.why.item5': 'Impact maken op de toekomst van AI in verschillende sectoren',
    'career.experts': 'Experts in ons team',
    'career.experience': 'Jaar ervaring',
    'career.projects.count': 'Projecten',
    'career.benefits.title': 'Onze',
    'career.benefits.highlight': 'Voordelen',
    'career.benefit.flexible.title': 'Flexibel werken',
    'career.benefit.flexible.desc': 'Hybride werkmodel met moderne apparatuur en flexibele werkuren',
    'career.benefit.learning.title': 'Leren & ontwikkeling',
    'career.benefit.learning.desc': 'Conferenties, trainingen en tijd voor persoonlijke projecten',
    'career.benefit.balance.title': 'Werk-leven balans',
    'career.benefit.balance.desc': 'Ruime vakantieregeling en mentale gezondheidsondersteuning',
    'career.benefit.package.title': 'Competitief pakket',
    'career.benefit.package.desc': 'Marktconform salaris, bonussen en aandelen opties',
    'career.benefit.culture.title': 'Geweldige cultuur',
    'career.benefit.culture.desc': 'Team events, gratis lunch en gezellige kantooromgeving',
    'career.positions.title': 'Open',
    'career.positions.highlight': 'Posities',
    'career.positions.featured': 'Featured',
    'career.positions.apply': 'Solliciteer nu',
    'career.positions.details': 'Meer details',
    'career.positions.requirements': 'Vereisten:',
    'career.process.title': 'Sollicitatieproces',
    'career.process.step1.title': 'Sollicitatie',
    'career.process.step1.desc': 'Verstuur je CV en motivatiebrief',
    'career.process.step2.title': 'Screening',
    'career.process.step2.desc': 'Eerste gesprek met HR',
    'career.process.step3.title': 'Technisch interview',
    'career.process.step3.desc': 'Gesprek met het team',
    'career.process.step4.title': 'Aanbod',
    'career.process.step4.desc': 'Welkom bij Cogniq AI!',
    'career.process.open.text': 'Zie je geen passende functie? Stuur ons een open sollicitatie - we horen graag van getalenteerde professionals!',
    'career.process.open.cta': 'Open sollicitatie',
    
    // Contact Page
    'contact.title': 'Neem',
    'contact.title.highlight': 'Contact',
    'contact.title.suffix': 'Op',
    'contact.subtitle': 'Klaar om uw AI-project te starten? Neem contact met ons op en laten we bespreken hoe we uw uitdagingen kunnen oplossen.',
    'contact.info.title': 'Contactinformatie',
    'contact.office.main': 'Hoofdkantoor',
    'contact.office.antwerp': 'Vestiging',
    'contact.phone': 'Telefoon',
    'contact.email': 'E-mail',
    'contact.hours': 'Openingstijden',
    'contact.form.title': 'Stuur ons een bericht',
    'contact.form.name': 'Volledige naam',
    'contact.form.name.placeholder': 'Jan Janssen',
    'contact.form.email': 'E-mailadres',
    'contact.form.email.placeholder': 'jan@voorbeeld.nl',
    'contact.form.company': 'Bedrijf',
    'contact.form.company.placeholder': 'Uw bedrijfsnaam',
    'contact.form.subject': 'Onderwerp',
    'contact.form.subject.placeholder': 'Waar kunnen we u mee helpen?',
    'contact.form.message': 'Bericht',
    'contact.form.message.placeholder': 'Vertel ons over uw project of uitdaging...',
    'contact.form.submit': 'Verstuur bericht',
    'contact.form.privacy': 'We respecteren uw privacy. Uw gegevens worden niet gedeeld met derden.',
    'contact.map.title': 'Bezoek ons kantoor',
    'contact.faq.title': 'Veelgestelde vragen',
    'contact.faq.q1': 'Wat kost een AI-project?',
    'contact.faq.a1': 'Kosten worden bepaald op basis van projectvereisten. Neem contact op voor een offerte.',
    'contact.faq.cta': 'Meer veelgestelde vragen',
    
    // News Page
    'news.title': 'Nieuws &',
    'news.title.highlight': 'Updates',
    'news.subtitle': 'Blijf op de hoogte van de laatste ontwikkelingen, projecten en innovaties bij Cogniq AI.',
    'news.categories': 'Categorieën',
    'news.featured': 'Featured',
    'news.read.more': 'Lees meer',
    'news.newsletter.title': 'Blijf op de hoogte',
    'news.newsletter.desc': 'Ontvang onze nieuwsbrief en mis geen enkel update over AI innovaties en bedrijfsinzichten.',
    'news.newsletter.placeholder': 'Uw e-mailadres',
    'news.newsletter.cta': 'Abonneren',

    // Project Cards Data
    'project.0.title': 'Controlesysteem voor de bovenleidingen van Brusselse trams',
    'project.0.description': 'De MIVB, de Brusselse openbaarvervoersmaatschappij, heeft een AI-gestuurd bewakingssysteem geïmplementeerd dat problemen met elektrische leidingen in realtime detecteert, waardoor de betrouwbaarheid en operationele efficiëntie van het tramnetwerk worden verbeterd.',
    'project.0.client': 'MIVB',
    'project.0.category': 'Transport & Mobiliteit',
    'project.1.title': 'Onderzoeksinstrument voor de evaluatie van behandelplannen',
    'project.1.description': 'Ion Beam Applications (IBA) werkte samen met B12 Consulting en de Rijksuniversiteit Groningen aan de ontwikkeling van een open-source platform voor onderzoekers in protontherapie, waardoor behandelplannen efficiënter kunnen worden opgesteld en geëvalueerd.',
    'project.1.client': 'IBA & RUG',
    'project.1.category': 'Gezondheidszorg',
    'project.2.title': 'Fotovoltaïsche installaties bewaken met machine learning',
    'project.2.description': 'Perpetum, een leider in de energiesector, verbeterde de monitoring van PV-centrales met een datagestuurde oplossing, waardoor de uitvaltijd werd verminderd door detectie van anomalieën en de financiële prestaties werden verbeterd door nauwkeurige voorspellingen van de energieproductie.',
    'project.2.client': 'Perpetum',
    'project.2.category': 'Energie',

    // Testimonials Data
    'testimonial.0.quote': 'De samenwerking met B12 heeft ons echt in staat gesteld om onze interne capaciteit op het gebied van machine learning en datawetenschappen uit te breiden. Ze hebben ons geholpen om deze capaciteit binnen ons team te laten groeien toen we onze traditionele business intelligence probeerden om te zetten naar een meer data-analytics-gedreven team. B12 deed het samen met ons, niet alleen voor ons, en gaf ons inzicht in hoe we dit zelf konden doen.',
    'testimonial.0.author': 'Rob Roemers',
    'testimonial.0.position': 'Hoofd gegevensanalyse',
    'testimonial.0.company': 'MIVB',
    'testimonial.1.quote': 'We hebben met B12 samengewerkt aan verschillende projecten die allemaal succesvol waren, grotendeels dankzij hun inzicht, technische expertise en innovatiecultuur. Ze hebben het opmerkelijke vermogen om te beginnen met een onvolledig idee dat we op tafel leggen, het uit te werken tot zijn volledige potentieel en een product af te leveren dat veel beter is dan het oorspronkelijke concept.',
    'testimonial.1.author': 'Mats Selen',
    'testimonial.1.position': 'Professor UIUC',
    'testimonial.1.company': 'Voorheen Novapta LLC',
    'testimonial.2.quote': 'Dankzij de begeleiding en het advies van B12 kon ons project verder gaan dan de doelstellingen die we aan het begin hadden vooropgesteld. Het B12-team is gedurende het hele project aandachtig gebleven voor onze behoeften en hun vaardigheden hebben ons in staat gesteld een tool te verkrijgen die in de voorste gelederen van de technologie staat en een aanzienlijke toegevoegde waarde heeft voor onze gebruikers.',
    'testimonial.2.author': 'David Baudrez',
    'testimonial.2.position': 'CEO',
    'testimonial.2.company': 'Gespodo',

    // Team Members Data
    'team.member.0.name': 'Dr. Sarah Johnson',
    'team.member.0.role': 'Chief Technology Officer',
    'team.member.0.description': '15+ jaar ervaring in AI-onderzoek en -implementatie',
    'team.member.0.skill.0': 'AI Strategy',
    'team.member.0.skill.1': 'Machine Learning',
    'team.member.0.skill.2': 'Deep Learning',
    'team.member.1.name': 'Marc Dubois',
    'team.member.1.role': 'Lead Data Scientist',
    'team.member.1.description': 'Specialist in machine learning algoritmes en data-analyse',
    'team.member.1.skill.0': 'Data Science',
    'team.member.1.skill.1': 'Python',
    'team.member.1.skill.2': 'TensorFlow',
    'team.member.2.name': 'Elena Rodriguez',
    'team.member.2.role': 'Senior Software Engineer',
    'team.member.2.description': 'Expert in schaalbare softwareoplossingen en cloud infrastructuur',
    'team.member.2.skill.0': 'Full-Stack',
    'team.member.2.skill.1': 'Cloud Architecture',
    'team.member.2.skill.2': 'DevOps',
    'team.member.3.name': 'Thomas Mueller',
    'team.member.3.role': 'AI Research Director',
    'team.member.3.description': 'Voormalig onderzoeker met focus op toegepaste AI-innovatie',
    'team.member.3.skill.0': 'Computer Vision',
    'team.member.3.skill.1': 'NLP',
    'team.member.3.skill.2': 'Research',
    'team.member.4.name': 'Sophie Laurent',
    'team.member.4.role': 'UX/UI Design Lead',
    'team.member.4.description': 'Specialist in intuïtieve interfaces voor complexe AI-systemen',
    'team.member.4.skill.0': 'User Experience',
    'team.member.4.skill.1': 'Interface Design',
    'team.member.4.skill.2': 'Prototyping',
    'team.member.5.name': 'Ahmed Hassan',
    'team.member.5.role': 'MLOps Engineer',
    'team.member.5.description': 'Expert in productie-gereed maken van ML-modellen',
    'team.member.5.skill.0': 'MLOps',
    'team.member.5.skill.1': 'Kubernetes',
    'team.member.5.skill.2': 'CI/CD',

    // Team Departments Data
    'team.dept.0.name': 'AI Research & Development',
    'team.dept.0.count': '12 experts',
    'team.dept.0.description': 'Cutting-edge onderzoek en ontwikkeling van AI-algoritmes',
    'team.dept.1.name': 'Software Engineering',
    'team.dept.1.count': '15 experts',
    'team.dept.1.description': 'Full-stack ontwikkeling en systeemintegratie',
    'team.dept.2.name': 'Data Science & Analytics',
    'team.dept.2.count': '10 experts',
    'team.dept.2.description': 'Data-analyse, visualisatie en business intelligence',
    'team.dept.3.name': 'UX/UI Design',
    'team.dept.3.count': '5 experts',
    'team.dept.3.description': 'Gebruikerservaring en interface design',

    // Sector Cards Data
    'sector.0.title': 'Middelgrote verzekeraars',
    'sector.0.description': 'AI-oplossingen voor risicobeoordeling, fraude detectie en klantservice optimalisatie specifiek voor middelgrote verzekeringsmaatschappijen.',
    'sector.0.solution.0': 'Geautomatiseerde risicobeoordeling',
    'sector.0.solution.1': 'Fraude detectie systemen',
    'sector.0.solution.2': 'Klantservice chatbots',
    'sector.0.solution.3': 'Premieberekening optimalisatie',
    'sector.0.caseStudy': 'AI-gedreven risicobeoordeling voor middelgrote verzekeraars',
    'sector.1.title': 'Professionele dienstverlening',
    'sector.1.description': 'Automatisering en AI-ondersteuning voor advocatuur, consultancy en boekhouding om efficiëntie te verhogen en kwaliteit te verbeteren.',
    'sector.1.solution.0': 'Juridische documenten analyse',
    'sector.1.solution.1': 'Geautomatiseerde boekhouding',
    'sector.1.solution.2': 'Consultant rapportage tools',
    'sector.1.solution.3': 'Client relationship management',
    'sector.1.caseStudy': 'Document analyse systeem voor advocatenkantoren',
    'sector.2.title': 'Zorgsector',
    'sector.2.description': 'AI-gedreven oplossingen voor klinieken, zorggroepen en kleinere zorginstellingen (geen ziekenhuizen) voor betere patiëntenzorg.',
    'sector.2.solution.0': 'Patiënt planning optimalisatie',
    'sector.2.solution.1': 'Medische data analyse',
    'sector.2.solution.2': 'Behandelplan ondersteuning',
    'sector.2.solution.3': 'Kwaliteitsbewaking systemen',
    'sector.2.caseStudy': 'Patiëntenzorg optimalisatie voor zorggroepen',
    'sector.3.title': 'Logistiek en Douane',
    'sector.3.description': 'Slimme oplossingen voor supply chain optimalisatie, douaneprocedures en transport efficiëntie verbetering.',
    'sector.3.solution.0': 'Route optimalisatie',
    'sector.3.solution.1': 'Douane documentatie automatisering',
    'sector.3.solution.2': 'Voorraad management',
    'sector.3.solution.3': 'Transport planning AI',
    'sector.3.caseStudy': 'Supply chain optimalisatie voor logistieke partners',
    'sector.4.title': 'Belasting optimalisatie voor bedrijven',
    'sector.4.description': 'AI-gedreven belastingoptimalisatie en compliance oplossingen voor bedrijven om fiscale efficiëntie te maximaliseren.',
    'sector.4.solution.0': 'Belasting planning tools',
    'sector.4.solution.1': 'Compliance monitoring',
    'sector.4.solution.2': 'Aftrek optimalisatie',
    'sector.4.solution.3': 'Fiscale rapportage automatisering',
    'sector.4.caseStudy': 'Belastingoptimalisatie systeem voor MKB bedrijven',
    'sector.5.title': 'Publieke sector (gemeenten, overheid)',
    'sector.5.description': 'Digitalisering en AI-oplossingen voor overheidsdiensten en gemeentelijke processen. (Later beschikbaar)',
    'sector.5.solution.0': 'Burger service optimalisatie',
    'sector.5.solution.1': 'Document verwerking',
    'sector.5.solution.2': 'Data analyse voor beleid',
    'sector.5.solution.3': 'Proces automatisering',
    'sector.5.caseStudy': 'Binnenkort beschikbaar - Publieke sector projecten',

    // Career Positions Data
    'career.job.0.title': 'Senior AI Engineer',
    'career.job.0.department': 'AI Research & Development',
    'career.job.0.location': 'Brussels, Hybrid',
    'career.job.0.type': 'Full-time',
    'career.job.0.salary': '€70.000 - €90.000',
    'career.job.0.description': 'We zoeken een ervaren AI Engineer om innovatieve machine learning oplossingen te ontwikkelen voor onze klanten.',
    'career.job.0.req.0': '5+ jaar ervaring met Python/TensorFlow',
    'career.job.0.req.1': 'PhD in AI/ML of gerelateerd veld',
    'career.job.0.req.2': 'Ervaring met cloud platforms',
    'career.job.1.title': 'Full-Stack Developer',
    'career.job.1.department': 'Software Engineering',
    'career.job.1.location': 'Antwerp, On-site',
    'career.job.1.type': 'Full-time',
    'career.job.1.salary': '€55.000 - €75.000',
    'career.job.1.description': 'Ontwikkel moderne webapplicaties en integreer AI-functionaliteiten in bestaande systemen.',
    'career.job.1.req.0': 'React/Node.js expertise',
    'career.job.1.req.1': '3+ jaar ervaring',
    'career.job.1.req.2': 'API integration ervaring',
    'career.job.2.title': 'Data Scientist',
    'career.job.2.department': 'Data Science & Analytics',
    'career.job.2.location': 'Brussels, Remote',
    'career.job.2.type': 'Full-time',
    'career.job.2.salary': '€60.000 - €80.000',
    'career.job.2.description': 'Analyseer complexe datasets en ontwikkel predictieve modellen voor diverse sectoren.',
    'career.job.2.req.0': 'Python/R expertise',
    'career.job.2.req.1': 'Statistiek achtergrond',
    'career.job.2.req.2': 'Business intelligence ervaring',
    'career.job.3.title': 'UX/UI Designer',
    'career.job.3.department': 'Design',
    'career.job.3.location': 'Brussels, Hybrid',
    'career.job.3.type': 'Full-time',
    'career.job.3.salary': '€50.000 - €65.000',
    'career.job.3.description': 'Ontwerp intuïtieve interfaces voor AI-gedreven applicaties en complexe data visualisaties.',
    'career.job.3.req.0': 'Figma/Sketch expertise',
    'career.job.3.req.1': 'User research ervaring',
    'career.job.3.req.2': 'Portfolio met B2B projecten',
    'career.job.4.title': 'DevOps Engineer',
    'career.job.4.department': 'Infrastructure',
    'career.job.4.location': 'Remote',
    'career.job.4.type': 'Contract',
    'career.job.4.salary': '€400 - €600/dag',
    'career.job.4.description': 'Beheer cloud infrastructuur en implementeer CI/CD pipelines voor ML-modellen.',
    'career.job.4.req.0': 'Kubernetes/Docker',
    'career.job.4.req.1': 'AWS/Azure expertise',
    'career.job.4.req.2': 'Infrastructure as Code',

    // News Items Data
    'news.item.0.title': 'B12 Consulting breidt AI-expertise uit met nieuwe partnerships',
    'news.item.0.excerpt': 'Nieuwe samenwerkingen met toonaangevende technologiepartners versterken onze capaciteit om innovatieve AI-oplossingen te leveren.',
    'news.item.0.date': '15 maart 2024',
    'news.item.0.author': 'Sarah Johnson',
    'news.item.0.category': 'Partnership',
    'news.item.0.readTime': '3 min',
    'news.item.1.title': 'Succesvolle implementatie van AI-monitoring systeem voor MIVB',
    'news.item.1.excerpt': 'Het nieuwe bewakingssysteem voor bovenleidingen verhoogt de betrouwbaarheid van het Brusselse tramnetwerk aanzienlijk.',
    'news.item.1.date': '28 februari 2024',
    'news.item.1.author': 'Marc Dubois',
    'news.item.1.category': 'Case Study',
    'news.item.1.readTime': '5 min',
    'news.item.2.title': 'B12 wint AI Innovation Award 2024',
    'news.item.2.excerpt': 'Onze innovatieve aanpak in healthcare AI wordt erkend met prestigieuze industrie award.',
    'news.item.2.date': '12 februari 2024',
    'news.item.2.author': 'Elena Rodriguez',
    'news.item.2.category': 'Award',
    'news.item.2.readTime': '2 min',
    'news.item.3.title': 'Nieuwe kantooropening in Antwerpen',
    'news.item.3.excerpt': 'Uitbreiding van ons team en dienstverlening met een nieuwe vestiging in het hart van de Vlaamse technologie-hub.',
    'news.item.3.date': '5 februari 2024',
    'news.item.3.author': 'Thomas Mueller',
    'news.item.3.category': 'Company News',
    'news.item.3.readTime': '4 min',
    'news.item.4.title': 'Gratis AI Workshop Series voor bedrijven',
    'news.item.4.excerpt': 'Leer hoe AI uw bedrijfsprocessen kan transformeren in onze nieuwe workshop serie voor Nederlandse en Belgische ondernemers.',
    'news.item.4.date': '20 januari 2024',
    'news.item.4.author': 'Sophie Laurent',
    'news.item.4.category': 'Event',
    'news.item.4.readTime': '3 min',
    'news.item.5.title': 'Onderzoeksresultaten gepubliceerd in Nature AI',
    'news.item.5.excerpt': 'Ons onderzoek naar ethische AI-implementatie wordt internationaal erkend en gepubliceerd in toonaangevend wetenschappelijk tijdschrift.',
    'news.item.5.date': '8 januari 2024',
    'news.item.5.author': 'Ahmed Hassan',
    'news.item.5.category': 'Research',
    'news.item.5.readTime': '6 min',

    // Contact Info Data
    'contact.info.0.title': 'Hoofdkantoor',
    'contact.info.0.detail.0': 'Amsterdam',
    'contact.info.0.detail.1': 'Nederland',
    'contact.info.1.title': 'Telefoon',
    'contact.info.1.detail.0': '+31 6 12345678',
    'contact.info.2.title': 'E-mail',
    'contact.info.2.detail.0': 'hello@cogniqai.nl',
    'contact.info.3.title': 'Openingstijden',
    'contact.info.3.detail.0': 'Ma-Vr: 9:00-18:00',
    'contact.info.3.detail.1': 'Za-Zo: Gesloten',
    'contact.office.0.city': 'Amsterdam',
    'contact.office.0.address': 'Amsterdam, Nederland',
    'contact.office.0.type': 'Hoofdkantoor',
    'contact.office.0.description': 'Ons hoofdkantoor in het hart van Amsterdam',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.projects': 'Projects',
    'nav.services': 'Services',
    'nav.sectors': 'Sectors',
    'nav.team': 'Team',
    'nav.news': 'News',
    'nav.career': 'Career',
    'nav.contact': 'Get in touch',
    
    // Hero Section
    'hero.title.ai': 'AI',
    'hero.title.transformation': 'TRANSFORMATION',
    'hero.title.now': 'NOW.',
    'hero.subtitle': 'Start your AI journey with a trusted partner',
    'hero.cta1': 'Discover our expertise',
    'hero.cta2': 'View projects',
    
    // Stats Section
    'stats.title': 'Fast results, high satisfaction, measurable impact',
    'stats.subtitle': 'We focus on what matters: happy clients, short delivery times and tangible value.',
    'stats.satisfaction': 'customer satisfaction',
    'stats.satisfaction.desc': 'Consistent rating for impact and collaboration',
    'stats.weeks': 'weeks to prototype',
    'stats.weeks.desc': 'From idea to first working AI solution in weeks',
    'stats.productivity': 'productivity improvement',
    'stats.productivity.desc': 'Demonstrable efficiency gains in implementations',
    'stats.cta': 'View results & cases',
    
    // Services Section
    'services.title': 'Our services',
    'services.subtitle': 'From AI-driven solutions to full software development - we help businesses transform with cutting-edge technology.',
    'services.ai.title': 'AI-powered solutions',
    'services.ai.desc': 'Custom-built, advanced artificial intelligence systems that meet unique needs',
    'services.software.title': 'Software development',
    'services.software.desc': 'Custom software solutions, tailored to specific needs',
    'services.data.title': 'Data management',
    'services.data.desc': 'Optimize data architecture for improved analytics',
    'services.innovation.title': 'Innovation strategy',
    'services.innovation.desc': 'Strategic exploration and planning for advanced artificial intelligence technology',
    'services.ux.title': 'UX & UI design',
    'services.ux.desc': 'Create intuitive, user-friendly interfaces for seamless system navigation',
    'services.ops.title': 'MLOps and DevOps',
    'services.ops.desc': 'Build robust, efficient frameworks for scalable, high-performing solutions',
    'services.more': 'More information →',
    'services.cta': 'View all services',
    
    // Case Studies Section
    'cases.title': 'Success stories',
    'cases.subtitle': 'Discover how we transform complex challenges into innovative solutions that have real impact.',
    'cases.result': 'Result:',
    'cases.view': 'View case study',
    'cases.cta': 'View all projects',
    
    // Testimonials Section
    'testimonials.title': 'What our clients say',
    'testimonials.subtitle': 'Our partnerships speak for themselves. Here are experiences from companies we have helped transform.',
    
    // Sectors Preview Section
    'sectors.title': 'Our sectors',
    'sectors.subtitle': 'We combine deep sector knowledge with cutting-edge AI technology.',
    'sectors.insurance.title': 'Mid-size insurers',
    'sectors.insurance.desc': 'AI solutions for risk assessment, fraud detection and customer service optimization in the insurance industry.',
    'sectors.professional.title': 'Professional services',
    'sectors.professional.desc': 'Automation and AI support for legal, consultancy and accounting to increase efficiency.',
    'sectors.healthcare.title': 'Healthcare sector',
    'sectors.healthcare.desc': 'AI-driven solutions for clinics, care groups and smaller healthcare institutions for better patient care.',
    'sectors.cta': 'Discover more',
    
    // CTA Section
    'cta.title': 'Want to start a project?',
    'cta.subtitle': "Let's talk",
    'cta.description': 'Ready to transform your business with AI? Let us discuss how we can turn your challenges into innovative solutions.',
    'cta.contact': 'Get in touch with us',
    'cta.projects': 'View our projects',
    'cta.call': 'Or call us directly:',
    'cta.phone': '+32 2 123 45 67',
    
    // Partners Section
    'partners.title': 'Associations and companies we proudly collaborate with',
    'partners.footer': 'And many other innovative partners in AI and technology',
    
    // Projects Page
    'projects.title': 'Our',
    'projects.title.highlight': 'Projects',
    'projects.subtitle': 'Discover how we transform complex challenges into innovative AI solutions for businesses across different sectors.',
    'projects.read.more': 'Read more →',
    'projects.cta.title': 'Do you have a project in mind?',
    'projects.cta.subtitle': 'Let us discuss together how we can turn your challenge into an innovative solution.',
    'projects.cta.button': 'Start your project',
    
    // Services Page
    'services.page.title': 'Our',
    'services.page.title.highlight': 'Services',
    'services.page.subtitle': 'From AI-driven solutions to full software development - we help businesses transform with cutting-edge technology.',
    'services.ai.features.ml': 'Machine Learning',
    'services.ai.features.dl': 'Deep Learning',
    'services.ai.features.cv': 'Computer Vision',
    'services.ai.features.nlp': 'Natural Language Processing',
    'services.software.features.custom': 'Custom Development',
    'services.software.features.api': 'API Integration',
    'services.software.features.cloud': 'Cloud Solutions',
    'services.software.features.mobile': 'Mobile Apps',
    'services.data.features.arch': 'Data Architecture',
    'services.data.features.etl': 'ETL Pipelines',
    'services.data.features.warehouse': 'Data Warehousing',
    'services.data.features.analytics': 'Analytics',
    'services.innovation.features.roadmap': 'Innovation Roadmap',
    'services.innovation.features.assessment': 'Technology Assessment',
    'services.innovation.features.strategy': 'Digital Strategy',
    'services.innovation.features.consulting': 'R&D Consulting',
    'services.ux.features.research': 'User Research',
    'services.ux.features.design': 'Interface Design',
    'services.ux.features.prototype': 'Prototyping',
    'services.ux.features.testing': 'Usability Testing',
    'services.ops.features.cicd': 'CI/CD Pipelines',
    'services.ops.features.deployment': 'Model Deployment',
    'services.ops.features.infrastructure': 'Infrastructure',
    'services.ops.features.monitoring': 'Monitoring',
    'services.additional.title': 'Additional',
    'services.additional.title.highlight': 'Specializations',
    'services.performance.title': 'Performance Optimization',
    'services.performance.desc': 'Improve system performance',
    'services.security.title': 'Security Consulting',
    'services.security.desc': 'Ensure security and compliance',
    'services.bi.title': 'Business Intelligence',
    'services.bi.desc': 'Data-driven decision making',
    'services.automation.title': 'Process Automation',
    'services.automation.desc': 'Automate business processes',
    'services.final.cta.title': 'Ready to start your project?',
    'services.final.cta.subtitle': 'Let us discuss how our expertise can take your business to the next level.',
    'services.final.cta.contact': 'Get in touch',
    'services.final.cta.projects': 'View our projects',
    
    // Specializations/Sectors Page
    'specializations.title': 'Our',
    'specializations.title.highlight': 'Sectors',
    'specializations.subtitle': 'We combine deep sector knowledge with cutting-edge AI technology to solve specific challenges in different industries.',
    'specializations.focus': 'Sector Focus',
    'specializations.solutions': 'Our solutions:',
    'specializations.case.study': 'Case Study:',
    'specializations.more.about': 'More about',
    'specializations.view.projects': 'View projects',
    'specializations.not.listed.title': 'Your sector not listed?',
    'specializations.not.listed.desc': 'We work with companies in various sectors. Contact us to discuss how we can solve your specific challenges.',
    'specializations.not.listed.cta': 'Discuss your project',
    
    // Footer
    'footer.description': 'Cogniq AI transforms businesses with innovative AI solutions. From strategy to implementation, we are your trusted partner in the AI revolution.',
    'footer.company': 'Company',
    'footer.services': 'Services',
    'footer.sectors': 'Sectors',
    'footer.company.about': 'About us',
    'footer.company.team': 'Team',
    'footer.company.career': 'Career',
    'footer.company.news': 'News',
    'footer.services.ai': 'AI solutions',
    'footer.services.software': 'Software development',
    'footer.services.data': 'Data engineering',
    'footer.services.consultancy': 'Consultancy',
    'footer.sectors.healthcare': 'Healthcare',
    'footer.sectors.energy': 'Energy',
    'footer.sectors.pharma': 'Pharmaceutical',
    'footer.sectors.transport': 'Transport',
    'footer.legal.privacy': 'Privacy policy',
    'footer.legal.terms': 'Terms and conditions',
    'footer.legal.cookies': 'Cookies',
    'footer.legal.gdpr': 'GDPR',
    'footer.copyright': '© 2024 Cogniq AI. All rights reserved.',
    
    // Team Page
    'team.title': 'Our',
    'team.title.highlight': 'Team',
    'team.subtitle': 'Meet the experts behind our AI solutions. A diverse team of data scientists, engineers and consultants.',
    'team.hero.title': 'Together we build the future of AI',
    'team.hero.desc': 'Our multidisciplinary team combines technical expertise with industry knowledge',
    'team.departments.title': 'Our',
    'team.departments.highlight': 'Departments',
    'team.members.title': 'Our',
    'team.members.highlight': 'Team',
    'team.join.title': 'Join our team',
    'team.join.desc': 'We are always looking for talented professionals who want to contribute to the future of AI.',
    'team.join.cta1': 'View vacancies',
    'team.join.cta2': 'Get in touch',
    
    // Career Page
    'career.title': 'Career at',
    'career.title.highlight': 'Cogniq AI',
    'career.subtitle': 'Join a team shaping the future of AI. At Cogniq AI we combine technical excellence with a great work culture.',
    'career.why.title': 'Why work at',
    'career.why.highlight': 'Cogniq AI',
    'career.why.item1': 'Work on cutting-edge AI projects for leading companies',
    'career.why.item2': 'Collaborate with a multidisciplinary team of experts',
    'career.why.item3': 'Contribute to open-source projects and research publications',
    'career.why.item4': 'Personal growth in a dynamic and innovative environment',
    'career.why.item5': 'Make an impact on the future of AI in various sectors',
    'career.experts': 'Experts on our team',
    'career.experience': 'Years experience',
    'career.projects.count': 'Projects',
    'career.benefits.title': 'Our',
    'career.benefits.highlight': 'Benefits',
    'career.benefit.flexible.title': 'Flexible working',
    'career.benefit.flexible.desc': 'Hybrid work model with modern equipment and flexible hours',
    'career.benefit.learning.title': 'Learning & development',
    'career.benefit.learning.desc': 'Conferences, training and time for personal projects',
    'career.benefit.balance.title': 'Work-life balance',
    'career.benefit.balance.desc': 'Generous vacation policy and mental health support',
    'career.benefit.package.title': 'Competitive package',
    'career.benefit.package.desc': 'Market-competitive salary, bonuses and stock options',
    'career.benefit.culture.title': 'Great culture',
    'career.benefit.culture.desc': 'Team events, free lunch and cozy office environment',
    'career.positions.title': 'Open',
    'career.positions.highlight': 'Positions',
    'career.positions.featured': 'Featured',
    'career.positions.apply': 'Apply now',
    'career.positions.details': 'More details',
    'career.positions.requirements': 'Requirements:',
    'career.process.title': 'Application process',
    'career.process.step1.title': 'Application',
    'career.process.step1.desc': 'Send your CV and motivation letter',
    'career.process.step2.title': 'Screening',
    'career.process.step2.desc': 'Initial interview with HR',
    'career.process.step3.title': 'Technical interview',
    'career.process.step3.desc': 'Interview with the team',
    'career.process.step4.title': 'Offer',
    'career.process.step4.desc': 'Welcome to Cogniq AI!',
    'career.process.open.text': "Don't see a suitable position? Send us an open application - we'd love to hear from talented professionals!",
    'career.process.open.cta': 'Open application',
    
    // Contact Page
    'contact.title': 'Get in',
    'contact.title.highlight': 'Touch',
    'contact.title.suffix': '',
    'contact.subtitle': 'Ready to start your AI project? Get in touch and let us discuss how we can solve your challenges.',
    'contact.info.title': 'Contact information',
    'contact.office.main': 'Head office',
    'contact.office.antwerp': 'Branch',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.hours': 'Opening hours',
    'contact.form.title': 'Send us a message',
    'contact.form.name': 'Full name',
    'contact.form.name.placeholder': 'John Doe',
    'contact.form.email': 'Email address',
    'contact.form.email.placeholder': 'john@example.com',
    'contact.form.company': 'Company',
    'contact.form.company.placeholder': 'Your company name',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'How can we help you?',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your project or challenge...',
    'contact.form.submit': 'Send message',
    'contact.form.privacy': 'We respect your privacy. Your data will not be shared with third parties.',
    'contact.map.title': 'Visit our office',
    'contact.faq.title': 'Frequently asked questions',
    'contact.faq.q1': 'What does an AI project cost?',
    'contact.faq.a1': 'Costs are determined based on project requirements. Contact us for a quote.',
    'contact.faq.cta': 'More frequently asked questions',
    
    // News Page
    'news.title': 'News &',
    'news.title.highlight': 'Updates',
    'news.subtitle': 'Stay informed about the latest developments, projects and innovations at Cogniq AI.',
    'news.categories': 'Categories',
    'news.featured': 'Featured',
    'news.read.more': 'Read more',
    'news.newsletter.title': 'Stay informed',
    'news.newsletter.desc': 'Receive our newsletter and don\'t miss any updates about AI innovations and business insights.',
    'news.newsletter.placeholder': 'Your email address',
    'news.newsletter.cta': 'Subscribe',

    // Project Cards Data
    'project.0.title': 'Monitoring system for overhead lines of Brussels trams',
    'project.0.description': 'MIVB, the Brussels public transport company, has implemented an AI-driven monitoring system that detects problems with electrical lines in real-time, improving the reliability and operational efficiency of the tram network.',
    'project.0.client': 'MIVB',
    'project.0.category': 'Transport & Mobility',
    'project.1.title': 'Research tool for treatment plan evaluation',
    'project.1.description': 'Ion Beam Applications (IBA) collaborated with B12 Consulting and the University of Groningen on developing an open-source platform for proton therapy researchers, enabling more efficient treatment plan creation and evaluation.',
    'project.1.client': 'IBA & RUG',
    'project.1.category': 'Healthcare',
    'project.2.title': 'Monitoring photovoltaic installations with machine learning',
    'project.2.description': 'Perpetum, a leader in the energy sector, improved PV plant monitoring with a data-driven solution, reducing downtime through anomaly detection and improving financial performance through accurate energy production forecasts.',
    'project.2.client': 'Perpetum',
    'project.2.category': 'Energy',

    // Testimonials Data
    'testimonial.0.quote': 'The collaboration with B12 really enabled us to expand our internal capacity in machine learning and data science. They helped us grow this capacity within our team when we tried to convert our traditional business intelligence into a more data-analytics-driven team. B12 did it with us, not just for us, and gave us insight into how we could do this ourselves.',
    'testimonial.0.author': 'Rob Roemers',
    'testimonial.0.position': 'Head of Data Analytics',
    'testimonial.0.company': 'MIVB',
    'testimonial.1.quote': 'We have collaborated with B12 on several projects that were all successful, largely thanks to their insight, technical expertise and innovation culture. They have the remarkable ability to start with an incomplete idea that we put on the table, work it out to its full potential and deliver a product that is much better than the original concept.',
    'testimonial.1.author': 'Mats Selen',
    'testimonial.1.position': 'Professor UIUC',
    'testimonial.1.company': 'Formerly Novapta LLC',
    'testimonial.2.quote': 'Thanks to the guidance and advice of B12, our project was able to go beyond the objectives we had set at the beginning. The B12 team remained attentive to our needs throughout the project and their skills enabled us to obtain a tool that is at the forefront of technology and has significant added value for our users.',
    'testimonial.2.author': 'David Baudrez',
    'testimonial.2.position': 'CEO',
    'testimonial.2.company': 'Gespodo',

    // Team Members Data
    'team.member.0.name': 'Dr. Sarah Johnson',
    'team.member.0.role': 'Chief Technology Officer',
    'team.member.0.description': '15+ years of experience in AI research and implementation',
    'team.member.0.skill.0': 'AI Strategy',
    'team.member.0.skill.1': 'Machine Learning',
    'team.member.0.skill.2': 'Deep Learning',
    'team.member.1.name': 'Marc Dubois',
    'team.member.1.role': 'Lead Data Scientist',
    'team.member.1.description': 'Specialist in machine learning algorithms and data analysis',
    'team.member.1.skill.0': 'Data Science',
    'team.member.1.skill.1': 'Python',
    'team.member.1.skill.2': 'TensorFlow',
    'team.member.2.name': 'Elena Rodriguez',
    'team.member.2.role': 'Senior Software Engineer',
    'team.member.2.description': 'Expert in scalable software solutions and cloud infrastructure',
    'team.member.2.skill.0': 'Full-Stack',
    'team.member.2.skill.1': 'Cloud Architecture',
    'team.member.2.skill.2': 'DevOps',
    'team.member.3.name': 'Thomas Mueller',
    'team.member.3.role': 'AI Research Director',
    'team.member.3.description': 'Former researcher focused on applied AI innovation',
    'team.member.3.skill.0': 'Computer Vision',
    'team.member.3.skill.1': 'NLP',
    'team.member.3.skill.2': 'Research',
    'team.member.4.name': 'Sophie Laurent',
    'team.member.4.role': 'UX/UI Design Lead',
    'team.member.4.description': 'Specialist in intuitive interfaces for complex AI systems',
    'team.member.4.skill.0': 'User Experience',
    'team.member.4.skill.1': 'Interface Design',
    'team.member.4.skill.2': 'Prototyping',
    'team.member.5.name': 'Ahmed Hassan',
    'team.member.5.role': 'MLOps Engineer',
    'team.member.5.description': 'Expert in production-ready ML models',
    'team.member.5.skill.0': 'MLOps',
    'team.member.5.skill.1': 'Kubernetes',
    'team.member.5.skill.2': 'CI/CD',

    // Team Departments Data
    'team.dept.0.name': 'AI Research & Development',
    'team.dept.0.count': '12 experts',
    'team.dept.0.description': 'Cutting-edge research and development of AI algorithms',
    'team.dept.1.name': 'Software Engineering',
    'team.dept.1.count': '15 experts',
    'team.dept.1.description': 'Full-stack development and system integration',
    'team.dept.2.name': 'Data Science & Analytics',
    'team.dept.2.count': '10 experts',
    'team.dept.2.description': 'Data analysis, visualization and business intelligence',
    'team.dept.3.name': 'UX/UI Design',
    'team.dept.3.count': '5 experts',
    'team.dept.3.description': 'User experience and interface design',

    // Sector Cards Data
    'sector.0.title': 'Mid-size insurers',
    'sector.0.description': 'AI solutions for risk assessment, fraud detection and customer service optimization specifically for mid-size insurance companies.',
    'sector.0.solution.0': 'Automated risk assessment',
    'sector.0.solution.1': 'Fraud detection systems',
    'sector.0.solution.2': 'Customer service chatbots',
    'sector.0.solution.3': 'Premium calculation optimization',
    'sector.0.caseStudy': 'AI-driven risk assessment for mid-size insurers',
    'sector.1.title': 'Professional services',
    'sector.1.description': 'Automation and AI support for legal, consultancy and accounting to increase efficiency and improve quality.',
    'sector.1.solution.0': 'Legal document analysis',
    'sector.1.solution.1': 'Automated accounting',
    'sector.1.solution.2': 'Consultant reporting tools',
    'sector.1.solution.3': 'Client relationship management',
    'sector.1.caseStudy': 'Document analysis system for law firms',
    'sector.2.title': 'Healthcare sector',
    'sector.2.description': 'AI-driven solutions for clinics, care groups and smaller healthcare institutions (no hospitals) for better patient care.',
    'sector.2.solution.0': 'Patient planning optimization',
    'sector.2.solution.1': 'Medical data analysis',
    'sector.2.solution.2': 'Treatment plan support',
    'sector.2.solution.3': 'Quality monitoring systems',
    'sector.2.caseStudy': 'Patient care optimization for care groups',
    'sector.3.title': 'Logistics and Customs',
    'sector.3.description': 'Smart solutions for supply chain optimization, customs procedures and transport efficiency improvement.',
    'sector.3.solution.0': 'Route optimization',
    'sector.3.solution.1': 'Customs documentation automation',
    'sector.3.solution.2': 'Inventory management',
    'sector.3.solution.3': 'Transport planning AI',
    'sector.3.caseStudy': 'Supply chain optimization for logistics partners',
    'sector.4.title': 'Tax optimization for businesses',
    'sector.4.description': 'AI-driven tax optimization and compliance solutions for businesses to maximize fiscal efficiency.',
    'sector.4.solution.0': 'Tax planning tools',
    'sector.4.solution.1': 'Compliance monitoring',
    'sector.4.solution.2': 'Deduction optimization',
    'sector.4.solution.3': 'Tax reporting automation',
    'sector.4.caseStudy': 'Tax optimization system for SME businesses',
    'sector.5.title': 'Public sector (municipalities, government)',
    'sector.5.description': 'Digitization and AI solutions for government services and municipal processes. (Available later)',
    'sector.5.solution.0': 'Citizen service optimization',
    'sector.5.solution.1': 'Document processing',
    'sector.5.solution.2': 'Data analysis for policy',
    'sector.5.solution.3': 'Process automation',
    'sector.5.caseStudy': 'Coming soon - Public sector projects',

    // Career Positions Data
    'career.job.0.title': 'Senior AI Engineer',
    'career.job.0.department': 'AI Research & Development',
    'career.job.0.location': 'Brussels, Hybrid',
    'career.job.0.type': 'Full-time',
    'career.job.0.salary': '€70,000 - €90,000',
    'career.job.0.description': 'We are looking for an experienced AI Engineer to develop innovative machine learning solutions for our clients.',
    'career.job.0.req.0': '5+ years experience with Python/TensorFlow',
    'career.job.0.req.1': 'PhD in AI/ML or related field',
    'career.job.0.req.2': 'Experience with cloud platforms',
    'career.job.1.title': 'Full-Stack Developer',
    'career.job.1.department': 'Software Engineering',
    'career.job.1.location': 'Antwerp, On-site',
    'career.job.1.type': 'Full-time',
    'career.job.1.salary': '€55,000 - €75,000',
    'career.job.1.description': 'Develop modern web applications and integrate AI functionalities into existing systems.',
    'career.job.1.req.0': 'React/Node.js expertise',
    'career.job.1.req.1': '3+ years experience',
    'career.job.1.req.2': 'API integration experience',
    'career.job.2.title': 'Data Scientist',
    'career.job.2.department': 'Data Science & Analytics',
    'career.job.2.location': 'Brussels, Remote',
    'career.job.2.type': 'Full-time',
    'career.job.2.salary': '€60,000 - €80,000',
    'career.job.2.description': 'Analyze complex datasets and develop predictive models for diverse sectors.',
    'career.job.2.req.0': 'Python/R expertise',
    'career.job.2.req.1': 'Statistics background',
    'career.job.2.req.2': 'Business intelligence experience',
    'career.job.3.title': 'UX/UI Designer',
    'career.job.3.department': 'Design',
    'career.job.3.location': 'Brussels, Hybrid',
    'career.job.3.type': 'Full-time',
    'career.job.3.salary': '€50,000 - €65,000',
    'career.job.3.description': 'Design intuitive interfaces for AI-driven applications and complex data visualizations.',
    'career.job.3.req.0': 'Figma/Sketch expertise',
    'career.job.3.req.1': 'User research experience',
    'career.job.3.req.2': 'Portfolio with B2B projects',
    'career.job.4.title': 'DevOps Engineer',
    'career.job.4.department': 'Infrastructure',
    'career.job.4.location': 'Remote',
    'career.job.4.type': 'Contract',
    'career.job.4.salary': '€400 - €600/day',
    'career.job.4.description': 'Manage cloud infrastructure and implement CI/CD pipelines for ML models.',
    'career.job.4.req.0': 'Kubernetes/Docker',
    'career.job.4.req.1': 'AWS/Azure expertise',
    'career.job.4.req.2': 'Infrastructure as Code',

    // News Items Data
    'news.item.0.title': 'B12 Consulting expands AI expertise with new partnerships',
    'news.item.0.excerpt': 'New collaborations with leading technology partners strengthen our capacity to deliver innovative AI solutions.',
    'news.item.0.date': 'March 15, 2024',
    'news.item.0.author': 'Sarah Johnson',
    'news.item.0.category': 'Partnership',
    'news.item.0.readTime': '3 min',
    'news.item.1.title': 'Successful implementation of AI monitoring system for MIVB',
    'news.item.1.excerpt': 'The new overhead line monitoring system significantly increases the reliability of the Brussels tram network.',
    'news.item.1.date': 'February 28, 2024',
    'news.item.1.author': 'Marc Dubois',
    'news.item.1.category': 'Case Study',
    'news.item.1.readTime': '5 min',
    'news.item.2.title': 'B12 wins AI Innovation Award 2024',
    'news.item.2.excerpt': 'Our innovative approach in healthcare AI is recognized with prestigious industry award.',
    'news.item.2.date': 'February 12, 2024',
    'news.item.2.author': 'Elena Rodriguez',
    'news.item.2.category': 'Award',
    'news.item.2.readTime': '2 min',
    'news.item.3.title': 'New office opening in Antwerp',
    'news.item.3.excerpt': 'Expansion of our team and services with a new location in the heart of the Flemish technology hub.',
    'news.item.3.date': 'February 5, 2024',
    'news.item.3.author': 'Thomas Mueller',
    'news.item.3.category': 'Company News',
    'news.item.3.readTime': '4 min',
    'news.item.4.title': 'Free AI Workshop Series for businesses',
    'news.item.4.excerpt': 'Learn how AI can transform your business processes in our new workshop series for Dutch and Belgian entrepreneurs.',
    'news.item.4.date': 'January 20, 2024',
    'news.item.4.author': 'Sophie Laurent',
    'news.item.4.category': 'Event',
    'news.item.4.readTime': '3 min',
    'news.item.5.title': 'Research results published in Nature AI',
    'news.item.5.excerpt': 'Our research on ethical AI implementation is internationally recognized and published in leading scientific journal.',
    'news.item.5.date': 'January 8, 2024',
    'news.item.5.author': 'Ahmed Hassan',
    'news.item.5.category': 'Research',
    'news.item.5.readTime': '6 min',

    // Contact Info Data
    'contact.info.0.title': 'Head Office',
    'contact.info.0.detail.0': 'Amsterdam',
    'contact.info.0.detail.1': 'Netherlands',
    'contact.info.1.title': 'Phone',
    'contact.info.1.detail.0': '+31 6 12345678',
    'contact.info.2.title': 'Email',
    'contact.info.2.detail.0': 'hello@cogniqai.nl',
    'contact.info.3.title': 'Opening hours',
    'contact.info.3.detail.0': 'Mon-Fri: 9:00-18:00',
    'contact.info.3.detail.1': 'Sat-Sun: Closed',
    'contact.office.0.city': 'Amsterdam',
    'contact.office.0.address': 'Amsterdam, Netherlands',
    'contact.office.0.type': 'Head Office',
    'contact.office.0.description': 'Our headquarters in the heart of Amsterdam',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('nl');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['nl']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};